# remap prefix from 'C-b' to 'C-a'
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# allow mouse usage
set -g mouse on

# reload tmux.conf
bind r source-file ~/.tmux.conf \; display "Reloaded!"

# Split vertically
bind v split-window -h

# Split horizontally
bind s split-window -v

