#!/usr/bin/bash

# setup function for a single config
function single_setup() {
  if [ $# -ne 2 ]; then
    echo "Needs two arguments"
    return
  fi

  local target="$HOME/.dotfiles/$1"
  local link="$HOME/$2"

  if [ ! -e $target ]; then
    echo "$target does not exist"
    return
  fi

  if [[ -e $link && -e $link.old ]]; then
    echo "$link and $link.old location already exist."
    return
  fi

  if [[ -e $link && ! -e $link.old ]]; then
    read -p "$link already exists. Continue? (y/N): " ans
    if [[ "$ans" != "y" ]]; then
      return
    fi

    read -p "Move it to $link.old? (y/N): " ans
    if [[ "$ans" == "y" ]]; then
      mv $link $link.old
    else
      rm $link
    fi
  fi

  ln -s $target $link
}

# execute single_setup for each config
single_setup i3 .config/i3
single_setup kitty .config/kitty
single_setup bash/bashrc .bashrc
single_setup bash/bashrc.d .bashrc.d
single_setup vim/vimrc .vimrc
single_setup vim/vim .vim

